
kind: Deployment
apiVersion: apps/v1
metadata:
  name: blzcloud-webcloud-dev-blazed
  namespace: dev-blazed-dev
  labels:
    app.kubernetes.io/name: blzcloud-webcloud-dev-blazed
    app.kubernetes.io/instance: blzcloud-webcloud-dev-blazed
    app.kubernetes.io/version: '20201201'
    app.kubernetes.io/component: WebCloud
    app.kubernetes.io/part-of: BlzCloud
    app.kubernetes.io/managed-by: blazedpath
    blazedEnv: dev
    accountCode: blazed
    enviromentCode: dev
    repositoryCode: blzcloud
    solutionCode: BlzCloud
    tier: frontend
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
    kubernetes.io/change-cause: '20201201'
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: blzcloud-webcloud-dev-blazed
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blzcloud-webcloud-dev-blazed
        app.kubernetes.io/instance: blzcloud-webcloud-dev-blazed
        app.kubernetes.io/version: '20201201'
        app.kubernetes.io/component: WebCloud
        app.kubernetes.io/part-of: BlzCloud
        app.kubernetes.io/managed-by: blazedpath
        blazedEnv: dev
        enviromentCode: dev
        repositoryCode: blzcloud
        solutionCode: BlzCloud
        tier: frontend
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '8080'
        kubernetes.io/change-cause: '20201201'
    spec:
      containers:
        - name: blzcloud-webcloud-dev-blazed
          image: 'docker.blazedpath.com/blazed/blzcloud-webcloud:20201123'
          imagePullPolicy: Always
          env:
            - name: blz_WebCloud_auth_openIdConfigurationEndpoint
              valueFrom:
                configMapKeyRef:
                  name: blzcloud-webcloud-dev-blazed-configmap
                  key: auth_openIdConfigurationEndpoint
            - name: blz_WebCloud_auth_authorizationEndpoint
              valueFrom:
                configMapKeyRef:
                  name: blzcloud-webcloud-dev-blazed-configmap
                  key: auth_authorizationEndpoint
            - name: blz_WebCloud_auth_tokenEndpoint
              valueFrom:
                configMapKeyRef:
                  name: blzcloud-webcloud-dev-blazed-configmap
                  key: auth_tokenEndpoint
            - name: blz_WebCloud_auth_userinfoEndpoint
              valueFrom:
                configMapKeyRef:
                  name: blzcloud-webcloud-dev-blazed-configmap
                  key: auth_userinfoEndpoint
            - name: blz_WebCloud_auth_checkSessionIframe
              valueFrom:
                configMapKeyRef:
                  name: blzcloud-webcloud-dev-blazed-configmap
                  key: auth_checkSessionIframe
            - name: blz_WebCloud_auth_endSessionEndpoint
              valueFrom:
                configMapKeyRef:
                  name: blzcloud-webcloud-dev-blazed-configmap
                  key: auth_endSessionEndpoint
            - name: blz_WebCloud_auth_jwksUri
              valueFrom:
                configMapKeyRef:
                  name: blzcloud-webcloud-dev-blazed-configmap
                  key: auth_jwksUri
            - name: blz_WebCloud_auth_clientId
              valueFrom:
                configMapKeyRef:
                  name: blzcloud-webcloud-dev-blazed-configmap
                  key: auth_clientId
            - name: blz_WebCloud_auth_clientSecret
              valueFrom:
                configMapKeyRef:
                  name: blzcloud-webcloud-dev-blazed-configmap
                  key: auth_clientSecret
            - name: blz_WebCloud_trace
              valueFrom:
                configMapKeyRef:
                  name: blzcloud-webcloud-dev-blazed-configmap
                  key: trace
            - name: blz_WebCloud_logError
              valueFrom:
                configMapKeyRef:
                  name: blzcloud-webcloud-dev-blazed-configmap
                  key: logError
            - name: blz_WebCloud_port
              valueFrom:
                configMapKeyRef:
                  name: blzcloud-webcloud-dev-blazed-configmap
                  key: port
            - name: blz_WebCloud_host
              valueFrom:
                configMapKeyRef:
                  name: blzcloud-webcloud-dev-blazed-configmap
                  key: host
            - name: blz_WebCloud_url
              valueFrom:
                configMapKeyRef:
                  name: blzcloud-webcloud-dev-blazed-configmap
                  key: url
            - name: blz_MsCloud_port
              valueFrom:
                configMapKeyRef:
                  name: blzcloud-mscloud-dev-blazed-configmap
                  key: port
            - name: blz_MsCloud_url
              valueFrom:
                configMapKeyRef:
                  name: blzcloud-mscloud-dev-blazed-configmap
                  key: url
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 120
            failureThreshold: 3
            periodSeconds: 240
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 250m
              memory: 500Mi
      serviceAccountName: blazed-dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: blzcloud-webcloud-dev-blazed
  namespace: dev-blazed-dev
  labels:
    app.kubernetes.io/name: blzcloud-webcloud-dev-blazed
    app.kubernetes.io/instance: blzcloud-webcloud-dev-blazed
    app.kubernetes.io/version: '20201201'
    app.kubernetes.io/component: WebCloud
    app.kubernetes.io/part-of: BlzCloud
    app.kubernetes.io/managed-by: blazedpath
    blazedEnv: dev
    accountCode: blazed
    enviromentCode: dev
    repositoryCode: blzcloud
    solutionCode: BlzCloud
    tier: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blzcloud-webcloud-dev-blazed
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75

---
kind: Service
apiVersion: v1
metadata:
  name: blzcloud-webcloud-dev-blazed
  namespace: dev-blazed-dev
  labels:
    app.kubernetes.io/name: blzcloud-webcloud-dev-blazed
    app.kubernetes.io/instance: blzcloud-webcloud-dev-blazed
    app.kubernetes.io/version: '20201201'
    app.kubernetes.io/component: WebCloud
    app.kubernetes.io/part-of: BlzCloud
    app.kubernetes.io/managed-by: blazedpath
    blazedEnv: dev
    accountCode: blazed
    enviromentCode: dev
    repositoryCode: blzcloud
    solutionCode: BlzCloud
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: blzcloud-webcloud-dev-blazed
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: blzcloud-webcloud-dev-blazed

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blzcloud-webcloud-dev-blazed
  namespace: dev-blazed-dev
  labels:
    app.kubernetes.io/name: blzcloud-webcloud-dev-blazed
    app.kubernetes.io/instance: blzcloud-webcloud-dev-blazed
    app.kubernetes.io/version: '20201201'
    app.kubernetes.io/component: WebCloud
    app.kubernetes.io/part-of: BlzCloud
    app.kubernetes.io/managed-by: blazedpath
    blazedEnv: dev
    accountCode: blazed
    enviromentCode: dev
    repositoryCode: blzcloud
    solutionCode: BlzCloud
    tier: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/limit-connections: '20480'
    nginx.ingress.kubernetes.io/limit-rpm: '300'
    nginx.ingress.kubernetes.io/limit-burst-multiplier: '600'
spec:
  tls:
    - hosts:
        - cloud.dev.blazedpath.com
      secretName: dev-blazedpath-com-tls
  rules:
    - host: cloud.dev.blazedpath.com
      http:
        paths:
          - backend:
              serviceName: blzcloud-webcloud-dev-blazed
              servicePort: 8080
