apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-local-tls
  namespace: cert-manager
spec:
  secretName: example-local-tls
  commonName: "*.example.local"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - example.local
    - "*.example.local"
